"""
    load_data_iris(path)

Load the Iris dataset from a CSV file, shuffle the observations, and split 
features from labels.

# AI Disclaimer
This helper method was generated by AI

# Arguments
- `path::String`: The file path to the CSV file (e.g., "src/data/Iris.csv").

# Returns
- `X::Matrix`: A matrix of feature values (columns 2 through 5).
- `y::Vector`: A vector of target labels.
"""
function load_data_iris(path::String) # use "src/data/Iris.csv" from within REPL
    df = read(path, DataFrame)

    p = shuffle(1:nrow(df))

    X = Matrix(df[p, 2:5])
    y = Vector(df.Species[p])

    return X, y
end